export interface PrahaData {
  num: number
  title: string
  district: string
  areas: string[]
  time: string
  imageUrl: string
  imageAlt: string
  imageCaption: string
  intro: string
  description: string
  coverage: string
  services: string[]
  process: { title: string; desc: string }[]
}

export const prahaData: Record<string, PrahaData> = {
  '1': {
    num: 1,
    title: 'Zámečník Praha 1',
    district: 'Praha 1',
    areas: ['Staré Město', 'Nové Město', 'Malá Strana', 'Hradčany', 'Josefov'],
    time: '20–40 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Prague_Old_Town_Square_view_from_Astronomical_Clock_tower.jpg?width=800',
    imageAlt: 'Zámečník Praha 1 - Staroměstské náměstí z Orloje',
    imageCaption: 'Praha 1 – Staroměstské náměstí',
    intro: 'Hledáte spolehlivého zámečníka v Praze 1? Zámečník Husák poskytuje profesionální zámečnické služby v celé Praze 1 – od Starého Města přes Malou Stranu až po Hradčany.',
    description: 'Praha 1 je historickým srdcem hlavního města. S množstvím historických budov, bytů i komerčních prostor zde denně řešíme nejrůznější zámečnické situace. Ať už jste se zabouchli v bytě na Starém Městě, potřebujete vyměnit zámek v kanceláři u Václavského náměstí, nebo hledáte zabezpečení pro váš obchod v Josefově – jsme tu pro vás.',
    coverage: 'Pokrýváme kompletně celou Prahu 1 včetně všech přilehlých ulic a lokalit. Díky centrální poloze Prahy 1 a našemu strategickému rozmístění techniků jsme schopni dorazit velmi rychle.',
    services: [
      'Otevírání zabouchnutých dveří v bytech a kancelářích',
      'Výměna cylindrických vložek a bezpečnostních zámků',
      'Montáž bezpečnostních dveří do bytových domů',
      'Otevírání a servis trezorů',
      'Instalace přístupových systémů pro SVJ',
      'Nouzové otevírání po vloupání',
    ],
    process: [
      { title: 'Zavolejte nám', desc: 'Na čísle 606 588 222 jsme dostupní nonstop.' },
      { title: 'Sdělíme cenu', desc: 'Po telefonu vám řekneme přesnou cenu a čas příjezdu.' },
      { title: 'Příjezd technika', desc: 'Zámečník dorazí do Prahy 1 do 20–40 minut.' },
      { title: 'Vyřešení problému', desc: 'Profesionálně a rychle vyřešíme váš problém.' },
    ],
  },
  '2': {
    num: 2,
    title: 'Zámečník Praha 2',
    district: 'Praha 2',
    areas: ['Vinohrady', 'Nusle', 'Vyšehrad', 'Nové Město', 'Albertov'],
    time: '20–40 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Namesti_miru.jpg?width=800',
    imageAlt: 'Zámečník Praha 2 - Náměstí Míru a kostel sv. Ludmily',
    imageCaption: 'Praha 2 – Náměstí Míru',
    intro: 'Potřebujete zámečníka v Praze 2? Poskytujeme rychlé a spolehlivé zámečnické služby ve Vinohradech, Nuslích, na Vyšehradě a v celé Praze 2.',
    description: 'Praha 2 patří k nejatraktivnějším rezidenčním čtvrtím Prahy. Vinohrady s krásnými činžovními domy, klidné Nusle i historický Vyšehrad – všude zde najdete naše spokojené zákazníky. Řešíme vše od zabouchnutých dveří po kompletní zabezpečení bytů.',
    coverage: 'Naši technici pokrývají celou Prahu 2 včetně všech vedlejších ulic a lokalit. Průměrný čas příjezdu do Prahy 2 je 20 minut.',
    services: [
      'Otevírání zabouchnutých dveří',
      'Výměna bezpečnostních vložek FAB, EVVA',
      'Montáž přídavných zámků',
      'Bezpečnostní dveře pro byty',
      'Masterkey systémy pro bytové domy',
      'Servis a oprava stávajících zámků',
    ],
    process: [
      { title: 'Zavolejte nám', desc: 'Na čísle 606 588 222 jsme dostupní nonstop.' },
      { title: 'Sdělíme cenu', desc: 'Přesná cena a odhad času příjezdu po telefonu.' },
      { title: 'Příjezd technika', desc: 'Zámečník dorazí do Prahy 2 do 20–40 minut.' },
      { title: 'Vyřešení problému', desc: 'Rychlé a profesionální vyřešení situace.' },
    ],
  },
  '3': {
    num: 3,
    title: 'Zámečník Praha 3',
    district: 'Praha 3',
    areas: ['Žižkov', 'Vinohrady (část)', 'Strašnice (část)', 'Olšany', 'Jarov'],
    time: '20–40 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Prag_Fernsehturm_Zizkov.jpg?width=800',
    imageAlt: 'Zámečník Praha 3 - Žižkovská televizní věž',
    imageCaption: 'Praha 3 – Žižkovský vysílač',
    intro: 'Zámečnická pohotovost v Praze 3 – Žižkov, Vinohrady, Jarov. Rychlý příjezd a profesionální služby za férové ceny.',
    description: 'Praha 3, známá především díky Žižkovu s jeho charakteristickou televizní věží, je oblíbenou rezidenční čtvrtí. Starší zástavba často vyžaduje modernizaci zabezpečení. Naši zámečníci mají bohaté zkušenosti s prací v historických i panelových domech.',
    coverage: 'Kompletní pokrytí Prahy 3 od Žižkova přes Olšany až po Jarov. Příjezd do 20–40 minut.',
    services: [
      'Nouzové otevírání dveří 24/7',
      'Výměna zámků ve starších domech',
      'Modernizace zabezpečení bytů',
      'Montáž bezpečnostních kování',
      'Otevírání trezorů a schránek',
      'Zabezpečení sklepních prostor',
    ],
    process: [
      { title: 'Zavolejte nám', desc: 'Linka 606 588 222 – nonstop.' },
      { title: 'Domluvíme detaily', desc: 'Cena a čas příjezdu ihned po telefonu.' },
      { title: 'Technik u vás', desc: 'Do 20–40 minut v celé Praze 3.' },
      { title: 'Problém vyřešen', desc: 'Profesionální servis bez kompromisů.' },
    ],
  },
  '4': {
    num: 4,
    title: 'Zámečník Praha 4',
    district: 'Praha 4',
    areas: ['Nusle', 'Podolí', 'Braník', 'Krč', 'Michle', 'Chodov', 'Modřany', 'Lhotka', 'Kunratice', 'Libuš'],
    time: '20–40 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pankr%C3%A1c,_Gemini.jpg?width=800',
    imageAlt: 'Zámečník Praha 4 - Pankrác City',
    imageCaption: 'Praha 4 – Pankrác',
    intro: 'Zámečnické služby v Praze 4 – od Nuslí a Podolí přes Krč až po Chodov a Modřany. Nonstop pohotovost.',
    description: 'Praha 4 je rozlehlý městský obvod zahrnující jak starší zástavbu v Nuslích a Michli, tak moderní sídliště na Chodově a v Modřanech. Naši zámečníci znají specifika všech typů bytů a domů v této oblasti.',
    coverage: 'Pokrýváme kompletně celou Prahu 4 – Nusle, Podolí, Braník, Krč, Michle, Chodov, Modřany, Lhotka, Kunratice i Libuš.',
    services: [
      'Otevírání bytů a domů',
      'Výměna vložek v panelových domech',
      'Bezpečnostní dveře pro rodinné domy',
      'Zabezpečení garáží a sklepů',
      'Elektronické přístupové systémy',
      'Servis zámků a kování',
    ],
    process: [
      { title: 'Kontaktujte nás', desc: 'Volejte 606 588 222 – jsme tu nonstop.' },
      { title: 'Cena předem', desc: 'Transparentní cenová nabídka po telefonu.' },
      { title: 'Rychlý příjezd', desc: 'V Praze 4 jsme do 20–40 minut.' },
      { title: 'Hotovo', desc: 'Kvalitní práce s zárukou.' },
    ],
  },
  '5': {
    num: 5,
    title: 'Zámečník Praha 5',
    district: 'Praha 5',
    areas: ['Smíchov', 'Košíře', 'Jinonice', 'Radlice', 'Hlubočepy', 'Motol', 'Stodůlky (část)', 'Barrandov'],
    time: '20–40 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/And%C4%9Bl_k%C5%99i%C5%BEovatka.jpg?width=800',
    imageAlt: 'Zámečník Praha 5 - Křižovatka Anděl',
    imageCaption: 'Praha 5 – Anděl',
    intro: 'Profesionální zámečník v Praze 5 – Smíchov, Košíře, Barrandov a další. Příjezd do 20–40 minut, nonstop.',
    description: 'Praha 5 nabízí širokou škálu zástavby od historického Smíchova přes rezidenční Košíře až po moderní Barrandov. Ať bydlíte kdekoliv v Praze 5, naši zámečníci jsou připraveni vám pomoci s jakýmkoliv problémem se zámky.',
    coverage: 'Celá Praha 5 – Smíchov, Košíře, Jinonice, Radlice, Hlubočepy, Motol, část Stodůlek a Barrandov.',
    services: [
      'Nouzové otevírání dveří',
      'Výměna a montáž zámků',
      'Bezpečnostní dveře a kování',
      'Zabezpečení komerčních prostor',
      'Autoklíče a otevírání aut',
      'Poradenství v oblasti zabezpečení',
    ],
    process: [
      { title: 'Zavolejte', desc: '606 588 222 – nonstop linka.' },
      { title: 'Dohodneme se', desc: 'Cena a čas příjezdu hned.' },
      { title: 'Přijedeme', desc: 'Do Prahy 5 za 20–40 minut.' },
      { title: 'Vyřešíme', desc: 'Profesionálně a bez poškození.' },
    ],
  },
  '6': {
    num: 6,
    title: 'Zámečník Praha 6',
    district: 'Praha 6',
    areas: ['Dejvice', 'Břevnov', 'Střešovice', 'Vokovice', 'Veleslavín', 'Bubeneč', 'Liboc', 'Ruzyně', 'Nebušice'],
    time: '20–40 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADt%C4%9Bzn%C3%A9_n%C3%A1m%C4%9Bst%C3%AD_(01).jpg?width=800',
    imageAlt: 'Zámečník Praha 6 - Vítězné náměstí Dejvice',
    imageCaption: 'Praha 6 – Vítězné náměstí',
    intro: 'Zámečnická pohotovost v Praze 6 – Dejvice, Břevnov, Střešovice, Vokovice a další lokality. Rychlý a spolehlivý servis.',
    description: 'Praha 6 je prestižní rezidenční čtvrť s vilovou zástavbou, ambasádami i moderními bytovými komplexy. Naši zámečníci mají zkušenosti s prací na všech typech nemovitostí v této oblasti, od historických vil po moderní smart bydlení.',
    coverage: 'Kompletní Praha 6 – Dejvice, Břevnov, Střešovice, Vokovice, Veleslavín, Bubeneč, Liboc, Ruzyně, Nebušice.',
    services: [
      'Otevírání dveří vil a bytů',
      'Bezpečnostní systémy pro vily',
      'Výměna zámků všech typů',
      'Montáž elektronických zámků',
      'Kamerové a přístupové systémy',
      'Zabezpečení ambasád a kanceláří',
    ],
    process: [
      { title: 'Kontakt', desc: 'Volejte 606 588 222 kdykoliv.' },
      { title: 'Cenová nabídka', desc: 'Férová cena sdělená předem.' },
      { title: 'Příjezd', desc: 'V Praze 6 do 20–40 minut.' },
      { title: 'Řešení', desc: 'Profesionální práce se zárukou.' },
    ],
  },
  '7': {
    num: 7,
    title: 'Zámečník Praha 7',
    district: 'Praha 7',
    areas: ['Holešovice', 'Letná', 'Troja', 'Bubeneč (část)'],
    time: '20–40 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Veletr%C5%BEn%C3%AD_pal%C3%A1c.jpg?width=800',
    imageAlt: 'Zámečník Praha 7 - Veletržní palác Holešovice',
    imageCaption: 'Praha 7 – Veletržní palác',
    intro: 'Zámečník v Praze 7 – Holešovice, Letná, Troja. Nonstop pohotovost s příjezdem do 20–40 minut.',
    description: 'Praha 7 je dynamicky se rozvíjející městská část. Holešovice prošly v posledních letech výraznou proměnou a dnes patří k nejžádanějším lokalitám. Pomáháme s zabezpečením jak nových loftových bytů, tak tradičních činžovních domů.',
    coverage: 'Celá Praha 7 – Holešovice, Letná, Troja a část Bubenče. Rychlý příjezd zaručen.',
    services: [
      'Otevírání moderních i tradičních zámků',
      'Zabezpečení loftových bytů',
      'Výměna vložek a kování',
      'Montáž bezpečnostních dveří',
      'Smart zámky a videovrátniky',
      'Servis zámků v komerčních prostorách',
    ],
    process: [
      { title: 'Zavolejte', desc: '606 588 222 – nonstop.' },
      { title: 'Domluvíme se', desc: 'Cena a čas příjezdu ihned.' },
      { title: 'Jsme u vás', desc: 'V Praze 7 do 20–40 minut.' },
      { title: 'Vyřešeno', desc: 'Rychle, čistě, profesionálně.' },
    ],
  },
  '8': {
    num: 8,
    title: 'Zámečník Praha 8',
    district: 'Praha 8',
    areas: ['Karlín', 'Libeň', 'Kobylisy', 'Bohnice', 'Čimice', 'Ďáblice', 'Střížkov', 'Dolní Chabry'],
    time: '20–40 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kostel_sv._Cyrila_a_Metod%C4%9Bje_v_Karl%C3%ADn%C4%9B.jpg?width=800',
    imageAlt: 'Zámečník Praha 8 - Kostel sv. Cyrila a Metoděje v Karlíně',
    imageCaption: 'Praha 8 – Karlín',
    intro: 'Zámečnická pohotovost v Praze 8 – Karlín, Libeň, Kobylisy, Bohnice. Profesionální služby nonstop.',
    description: 'Praha 8 je pestrý městský obvod – od moderního Karlína přes tradiční Libeň až po klidné Kobylisy a Bohnice. Naši zámečníci znají specifika všech částí a jsou připraveni pomoci s jakýmkoliv typem zámku nebo dveří.',
    coverage: 'Celá Praha 8 – Karlín, Libeň, Kobylisy, Bohnice, Čimice, Ďáblice, Střížkov, Dolní Chabry.',
    services: [
      'Otevírání bytů a kanceláří',
      'Výměna zámků v novostavbách',
      'Zabezpečení starších domů',
      'Montáž přístupových systémů',
      'Opravy a servis zámků',
      'Bezpečnostní audit nemovitosti',
    ],
    process: [
      { title: 'Volejte', desc: '606 588 222 – jsme tu pro vás.' },
      { title: 'Cena předem', desc: 'Žádná překvapení, férové ceny.' },
      { title: 'Rychlý příjezd', desc: 'V Praze 8 za 20–40 minut.' },
      { title: 'Profesionální servis', desc: 'Kvalita a záruka na práci.' },
    ],
  },
  '9': {
    num: 9,
    title: 'Zámečník Praha 9',
    district: 'Praha 9',
    areas: ['Vysočany', 'Prosek', 'Letňany', 'Černý Most', 'Kyje', 'Hloubětín', 'Kbely', 'Čakovice', 'Satalice'],
    time: '20–40 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/O2_Arena_Prague_2.jpg?width=800',
    imageAlt: 'Zámečník Praha 9 - O2 Arena Vysočany',
    imageCaption: 'Praha 9 – O2 Arena',
    intro: 'Zámečník v Praze 9 – Vysočany, Prosek, Letňany, Černý Most a další. Nonstop pohotovost s rychlým příjezdem.',
    description: 'Praha 9 je rozlehlý městský obvod s dynamickým rozvojem. Od moderních Vysočan přes sídliště na Proseku a Letňanech až po klidné Kbely – všude zde poskytujeme spolehlivé zámečnické služby.',
    coverage: 'Kompletní Praha 9 – Vysočany, Prosek, Letňany, Černý Most, Kyje, Hloubětín, Kbely, Čakovice, Satalice.',
    services: [
      'Otevírání zabouchnutých dveří',
      'Výměna vložek v panelových domech',
      'Zabezpečení novostaveb',
      'Montáž bezpečnostních dveří',
      'Autoklíče a otevírání aut',
      'Komplexní bezpečnostní řešení',
    ],
    process: [
      { title: 'Zavolejte nám', desc: '606 588 222 – nonstop dostupnost.' },
      { title: 'Dohodneme podmínky', desc: 'Transparentní cena po telefonu.' },
      { title: 'Technik na cestě', desc: 'V Praze 9 do 20–40 minut.' },
      { title: 'Vše vyřešeno', desc: 'Profesionální práce se zárukou.' },
    ],
  },
  '10': {
    num: 10,
    title: 'Zámečník Praha 10',
    district: 'Praha 10',
    areas: ['Vršovice', 'Strašnice', 'Hostivař', 'Malešice', 'Záběhlice', 'Michle (část)', 'Vinohrady (část)', 'Štěrboholy'],
    time: '15–30 minut',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1ovice_n%C3%A1m%C4%9Bst%C3%AD_Svatopluka_%C4%8Cecha.jpg?width=800',
    imageAlt: 'Zámečník Praha 10 - Náměstí Svatopluka Čecha ve Vršovicích',
    imageCaption: 'Praha 10 – Vršovice',
    intro: 'Praha 10 je naše domovská čtvrť! Sídlíme na adrese Herbenova 727/38 a díky tomu jsme v celé Praze 10 nejrychleji – obvykle do 15–30 minut.',
    description: 'Praha 10 je pro nás domov. Naše sídlo na Herbenově ulici nám umožňuje být v celé Praze 10 nejrychleji ze všech částí města. Ať už jste ve Vršovicích, Strašnicích, Hostivaři nebo Malešicích – jsme u vás dříve než kdokoliv jiný.',
    coverage: 'Praha 10 je naše domovská čtvrť – Vršovice, Strašnice, Hostivař, Malešice, Záběhlice, část Michle, část Vinohrad, Štěrboholy. Nejrychlejší příjezd ze všech obvodů!',
    services: [
      'Otevírání dveří – nejrychlejší příjezd',
      'Výměna vložek a zámků',
      'Montáž bezpečnostních dveří',
      'Zabezpečení rodinných domů',
      'Elektronické zámky a systémy',
      'Pravidelný servis a údržba zámků',
    ],
    process: [
      { title: 'Zavolejte', desc: '606 588 222 – jsme za rohem!' },
      { title: 'Okamžitá reakce', desc: 'Cena a čas příjezdu ihned.' },
      { title: 'Bleskový příjezd', desc: 'V Praze 10 za pouhých 15–30 minut!' },
      { title: 'Hotovo', desc: 'Kvalitní práce od místních profíků.' },
    ],
  },
}
